<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '净水器',
    'measure_unit' => '台',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 9,
    'level' => 0,
    'id' => '1',
    'name' => '净水器',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '过滤级数',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 7,
    'level' => 1,
    'id' => '5',
    'name' => '过滤级数',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '三级过滤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '57',
    'name' => '三级过滤',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '八级过滤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '62',
    'name' => '八级过滤',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '一级过滤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 2,
    'id' => '55',
    'name' => '一级过滤',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '五级过滤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '59',
    'name' => '五级过滤',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '二级过滤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '56',
    'name' => '二级过滤',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '九级过滤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '63',
    'name' => '九级过滤',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '六级过滤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '60',
    'name' => '六级过滤',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '四级过滤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '58',
    'name' => '四级过滤',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '七级过滤',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '61',
    'name' => '七级过滤',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '水质',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '水质',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '纯净水',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '67',
    'name' => '纯净水',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '矿物质水',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '矿物质水',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '软水',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '软水',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '磁化水',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '磁化水',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '配件',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '15',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '配件',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '烧结活性炭',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '86',
    'name' => '烧结活性炭',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => 'PP棉-5微米',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '83',
    'name' => 'PP棉-5微米',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '阀门',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '阀门',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '水管',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '水管',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '紫外线灯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '87',
    'name' => '紫外线灯',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '反渗透膜（RO膜）',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '反渗透膜（RO膜）',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '扳手',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '扳手',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '套装滤芯',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '81',
    'name' => '套装滤芯',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '水管快接',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '水管快接',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '电磁阀',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '88',
    'name' => '电磁阀',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '颗粒活性炭',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => '颗粒活性炭',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '增压泵',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '增压泵',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => 'PP棉-1微米',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '82',
    'name' => 'PP棉-1微米',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '尾水电磁阀',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '92',
    'name' => '尾水电磁阀',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '控制板',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '89',
    'name' => '控制板',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '过滤',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '过滤',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '前置过滤机',
    'measure_unit' => '',
    'parent_id' => '71',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '前置过滤机',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '超滤机',
    'measure_unit' => '',
    'parent_id' => '71',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '超滤机',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '反渗透（RO）机',
    'measure_unit' => '',
    'parent_id' => '71',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '反渗透（RO）机',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '软水机',
    'measure_unit' => '',
    'parent_id' => '71',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '软水机',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '安装',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '76',
    'name' => '安装',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '壁挂机',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '壁挂机',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '厨下机',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '厨下机',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '饮水机净水器',
    'measure_unit' => '',
    'parent_id' => '76',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '饮水机净水器',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '功能',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => '功能',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '杀菌',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '65',
    'name' => '杀菌',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '初级过滤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '初级过滤',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '除水垢',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => '除水垢',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '空气净化器',
    'measure_unit' => '台',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 2,
    'level' => 0,
    'id' => '6',
    'name' => '空气净化器',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '非连动',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '非连动',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '连动',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '连动',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '防护器具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '33',
    'name' => '防护器具',
  ),
);
?>